#ifndef MICROPY_INCLUDED_EIGEN718_EG800ZCN_LA_MPCONFIGBOARD_H
#define MICROPY_INCLUDED_EIGEN718_EG800ZCN_LA_MPCONFIGBOARD_H

#define MICROPY_HW_BOARD_NAME "EG800ZCN_LA"
#define MICROPY_QPY_BOARD_NAME "EG800ZCN_LA"
#define MICROPY_HW_MCU_NAME "EC718 UniRTOS"
#define MICROPY_PY_SYS_PLATFORM "quectel-unirtos"

#define MICROPY_QPY_REPL_PORT (7)
#define MICROPY_QPY_REPL_BAUD (QOSA_UART_BAUD_115200)
#define MICROPY_QPY_GC_HEAP_SIZE (512 * 1024)
#define MICROPY_QPY_MAIN_TASK_STACK_SIZE (32 * 1024)
#define MICROPY_QPY_THREAD_STACK_SIZE (8 * 1024)
#define MICROPY_QPY_USRFS_AUTO_FORMAT (0)

#define MICROPY_QPY_MODULE_ATCMD (1)
#define MICROPY_QPY_MODULE_EXAMPLE (1)
#define MICROPY_QPY_MODULE_UOS (1)
#define MICROPY_QPY_MODULE_MACHINE (1)
#define MICROPY_QPY_MODULE_MISC (1)
#define MICROPY_QPY_MODULE_DATACALL (1)
#define MICROPY_QPY_MODULE_MODEM (1)
#define MICROPY_QPY_MODULE_UTIME (1)
#define MICROPY_QPY_MODULE_SMS (1)
#define MICROPY_QPY_MODULE_SIM (1)
#define MICROPY_QPY_MODULE_NET (1)
#define MICROPY_QPY_MODULE_USOCKET (1)
#define MICROPY_QPY_MODULE_OSTIMER (1)

#define MICROPY_QPY_MODULE_UJSON (1)
#define MICROPY_QPY_MODULE_UBINASCII (1)
#define MICROPY_QPY_MODULE_USTRUCT (1)
#define MICROPY_QPY_MODULE_URANDOM (1)
#define MICROPY_QPY_MODULE_UERRNO (1)
#define MICROPY_QPY_MODULE_USELECT (1)
#define MICROPY_QPY_MODULE_UCOLLECTIONS (1)
#define MICROPY_QPY_MODULE_MATH (1)
#define MICROPY_QPY_MODULE_UZLIB (1)

#define MICROPY_QPY_MODULE_AUDIO (0)
#define MICROPY_QPY_MODULE_FOTA (1)
#define MICROPY_QPY_MODULE_QUECIOT (0)
#define MICROPY_QPY_MODULE_LVGL (0)
#define MICROPY_QPY_MODULE_CAMERA (0)
#define MICROPY_QPY_MODULE_BLE (0)
#define MICROPY_QPY_MODULE_BT (0)
#define MICROPY_QPY_MODULE_ETHERNET (0)
#define MICROPY_QPY_MODULE_QUECGNSS (0)
#define MICROPY_QPY_MODULE_WIFI (0)

#if MICROPY_QPY_MODULE_MACHINE
#define MICROPY_QPY_MACHINE_UART (1)
#define MICROPY_QPY_MACHINE_PIN (1)
#define MICROPY_QPY_MACHINE_TIMER (1)
#define MICROPY_QPY_MACHINE_RTC (1)
#define MICROPY_QPY_MACHINE_WDT (1)
#define MICROPY_QPY_MACHINE_EXTINT (1)
#define MICROPY_QPY_MACHINE_KEY (1)
#define MICROPY_QPY_MACHINE_I2C (1)
#define MICROPY_QPY_MACHINE_SPI (1)
#endif

#if MICROPY_QPY_MODULE_MISC
#define MICROPY_QPY_MISC_POWER (1)
#define MICROPY_QPY_MISC_ADC (1)
#define MICROPY_QPY_MISC_PWM (1)
#define MICROPY_QPY_MISC_POWERKEY (1)
#define MICROPY_QPY_MISC_TEMPERATURE (1)
#define MICROPY_QPY_MISC_USB (1)
#define MICROPY_QPY_MISC_USBNET (1)
#endif

#define MICROPY_QPY_I2C_DEFAULT_SCL_PIN (67)
#define MICROPY_QPY_I2C_DEFAULT_SDA_PIN (66)
#define MICROPY_QPY_I2C_DEFAULT_PIN_FUNC (2)

#define MICROPY_QPY_SPI_DEFAULT_MOSI_PIN (50)
#define MICROPY_QPY_SPI_DEFAULT_MISO_PIN (51)
#define MICROPY_QPY_SPI_DEFAULT_CLK_PIN (53)
#define MICROPY_QPY_SPI_DEFAULT_CS_PIN (52)
#define MICROPY_QPY_SPI_DEFAULT_PIN_FUNC (1)

#define MICROPY_QPY_PWM_DEFAULT_PIN (21)
#define MICROPY_QPY_PWM_DEFAULT_PIN_FUNC (5)

#define MICROPY_QPY_FROZEN_BOOT (1)
#define MICROPY_QPY_FROZEN_APP_FOTA (1)
#define MICROPY_QPY_FROZEN_CHECKNET (1)
#define MICROPY_QPY_FROZEN_DATACALL (1)
#define MICROPY_QPY_FROZEN_LOG (1)
#define MICROPY_QPY_FROZEN_NTPTIME (1)
#define MICROPY_QPY_FROZEN_QL_FS (1)
#define MICROPY_QPY_FROZEN_QUEUE (1)
#define MICROPY_QPY_FROZEN_REQUEST (1)
#define MICROPY_QPY_FROZEN_SIM (1)
#define MICROPY_QPY_FROZEN_SYSTEM (1)
#define MICROPY_QPY_FROZEN_URE (1)
#define MICROPY_QPY_FROZEN_UMQTT (1)
#define MICROPY_QPY_FROZEN_YMODEM (1)

#endif
